#!/bin/sh
# this script is meant to run in the background and wait for you to entire
# a command that takes much longer than you expected it to.
# it will then notify you in your preferred fashion
#
# script originally written by lizardthunder in 2016
# https://github.com/lizardthunder/longAssTimed
